import './styles/index.scss'

import './js/animate'
import './js/banner'
import './js/custom-slider'
import './js/footer'
import './js/header-menu'
import './js/present-block'
import './js/short-catalog'
import './js/popup-catalog'
import './js/popup-basket'
